/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SellersRouteImport } from './routes/sellers'
import { Route as RealtorsRouteImport } from './routes/realtors'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HomeLoansRouteImport } from './routes/home-loans'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as BuyersRouteImport } from './routes/buyers'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as OnboardingIntakeRouteImport } from './routes/onboarding.intake'
import { Route as OnboardingAgreementRouteImport } from './routes/onboarding.agreement'
import { Route as CommunitiesInventoryRouteImport } from './routes/communities_.inventory'
import { Route as OnboardingIntakeSuccessRouteImport } from './routes/onboarding.intake.success'
import { Route as OnboardingAgreementSuccessRouteImport } from './routes/onboarding.agreement.success'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SellersRoute = SellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const RealtorsRoute = RealtorsRouteImport.update({
  id: '/realtors',
  path: '/realtors',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeLoansRoute = HomeLoansRouteImport.update({
  id: '/home-loans',
  path: '/home-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyersRoute = BuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingIntakeRoute = OnboardingIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingAgreementRoute = OnboardingAgreementRouteImport.update({
  id: '/agreement',
  path: '/agreement',
  getParentRoute: () => OnboardingRoute,
} as any)
const CommunitiesInventoryRoute = CommunitiesInventoryRouteImport.update({
  id: '/communities_/inventory',
  path: '/communities/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIntakeSuccessRoute = OnboardingIntakeSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => OnboardingIntakeRoute,
} as any)
const OnboardingAgreementSuccessRoute =
  OnboardingAgreementSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => OnboardingAgreementRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/buyers': typeof BuyersRoute
  '/communities': typeof CommunitiesRoute
  '/contact': typeof ContactRoute
  '/home-loans': typeof HomeLoansRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/realtors': typeof RealtorsRoute
  '/sellers': typeof SellersRoute
  '/terms': typeof TermsRoute
  '/communities/inventory': typeof CommunitiesInventoryRoute
  '/onboarding/agreement': typeof OnboardingAgreementRouteWithChildren
  '/onboarding/intake': typeof OnboardingIntakeRouteWithChildren
  '/onboarding/': typeof OnboardingIndexRoute
  '/onboarding/agreement/success': typeof OnboardingAgreementSuccessRoute
  '/onboarding/intake/success': typeof OnboardingIntakeSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/buyers': typeof BuyersRoute
  '/communities': typeof CommunitiesRoute
  '/contact': typeof ContactRoute
  '/home-loans': typeof HomeLoansRoute
  '/privacy': typeof PrivacyRoute
  '/realtors': typeof RealtorsRoute
  '/sellers': typeof SellersRoute
  '/terms': typeof TermsRoute
  '/communities/inventory': typeof CommunitiesInventoryRoute
  '/onboarding/agreement': typeof OnboardingAgreementRouteWithChildren
  '/onboarding/intake': typeof OnboardingIntakeRouteWithChildren
  '/onboarding': typeof OnboardingIndexRoute
  '/onboarding/agreement/success': typeof OnboardingAgreementSuccessRoute
  '/onboarding/intake/success': typeof OnboardingIntakeSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/buyers': typeof BuyersRoute
  '/communities': typeof CommunitiesRoute
  '/contact': typeof ContactRoute
  '/home-loans': typeof HomeLoansRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/realtors': typeof RealtorsRoute
  '/sellers': typeof SellersRoute
  '/terms': typeof TermsRoute
  '/communities_/inventory': typeof CommunitiesInventoryRoute
  '/onboarding/agreement': typeof OnboardingAgreementRouteWithChildren
  '/onboarding/intake': typeof OnboardingIntakeRouteWithChildren
  '/onboarding/': typeof OnboardingIndexRoute
  '/onboarding/agreement/success': typeof OnboardingAgreementSuccessRoute
  '/onboarding/intake/success': typeof OnboardingIntakeSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/buyers'
    | '/communities'
    | '/contact'
    | '/home-loans'
    | '/onboarding'
    | '/privacy'
    | '/realtors'
    | '/sellers'
    | '/terms'
    | '/communities/inventory'
    | '/onboarding/agreement'
    | '/onboarding/intake'
    | '/onboarding/'
    | '/onboarding/agreement/success'
    | '/onboarding/intake/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/buyers'
    | '/communities'
    | '/contact'
    | '/home-loans'
    | '/privacy'
    | '/realtors'
    | '/sellers'
    | '/terms'
    | '/communities/inventory'
    | '/onboarding/agreement'
    | '/onboarding/intake'
    | '/onboarding'
    | '/onboarding/agreement/success'
    | '/onboarding/intake/success'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/buyers'
    | '/communities'
    | '/contact'
    | '/home-loans'
    | '/onboarding'
    | '/privacy'
    | '/realtors'
    | '/sellers'
    | '/terms'
    | '/communities_/inventory'
    | '/onboarding/agreement'
    | '/onboarding/intake'
    | '/onboarding/'
    | '/onboarding/agreement/success'
    | '/onboarding/intake/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  BuyersRoute: typeof BuyersRoute
  CommunitiesRoute: typeof CommunitiesRoute
  ContactRoute: typeof ContactRoute
  HomeLoansRoute: typeof HomeLoansRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RealtorsRoute: typeof RealtorsRoute
  SellersRoute: typeof SellersRoute
  TermsRoute: typeof TermsRoute
  CommunitiesInventoryRoute: typeof CommunitiesInventoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers': {
      id: '/sellers'
      path: '/sellers'
      fullPath: '/sellers'
      preLoaderRoute: typeof SellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realtors': {
      id: '/realtors'
      path: '/realtors'
      fullPath: '/realtors'
      preLoaderRoute: typeof RealtorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-loans': {
      id: '/home-loans'
      path: '/home-loans'
      fullPath: '/home-loans'
      preLoaderRoute: typeof HomeLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyers': {
      id: '/buyers'
      path: '/buyers'
      fullPath: '/buyers'
      preLoaderRoute: typeof BuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/intake': {
      id: '/onboarding/intake'
      path: '/intake'
      fullPath: '/onboarding/intake'
      preLoaderRoute: typeof OnboardingIntakeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/agreement': {
      id: '/onboarding/agreement'
      path: '/agreement'
      fullPath: '/onboarding/agreement'
      preLoaderRoute: typeof OnboardingAgreementRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/communities_/inventory': {
      id: '/communities_/inventory'
      path: '/communities/inventory'
      fullPath: '/communities/inventory'
      preLoaderRoute: typeof CommunitiesInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/intake/success': {
      id: '/onboarding/intake/success'
      path: '/success'
      fullPath: '/onboarding/intake/success'
      preLoaderRoute: typeof OnboardingIntakeSuccessRouteImport
      parentRoute: typeof OnboardingIntakeRoute
    }
    '/onboarding/agreement/success': {
      id: '/onboarding/agreement/success'
      path: '/success'
      fullPath: '/onboarding/agreement/success'
      preLoaderRoute: typeof OnboardingAgreementSuccessRouteImport
      parentRoute: typeof OnboardingAgreementRoute
    }
  }
}

interface OnboardingAgreementRouteChildren {
  OnboardingAgreementSuccessRoute: typeof OnboardingAgreementSuccessRoute
}

const OnboardingAgreementRouteChildren: OnboardingAgreementRouteChildren = {
  OnboardingAgreementSuccessRoute: OnboardingAgreementSuccessRoute,
}

const OnboardingAgreementRouteWithChildren =
  OnboardingAgreementRoute._addFileChildren(OnboardingAgreementRouteChildren)

interface OnboardingIntakeRouteChildren {
  OnboardingIntakeSuccessRoute: typeof OnboardingIntakeSuccessRoute
}

const OnboardingIntakeRouteChildren: OnboardingIntakeRouteChildren = {
  OnboardingIntakeSuccessRoute: OnboardingIntakeSuccessRoute,
}

const OnboardingIntakeRouteWithChildren =
  OnboardingIntakeRoute._addFileChildren(OnboardingIntakeRouteChildren)

interface OnboardingRouteChildren {
  OnboardingAgreementRoute: typeof OnboardingAgreementRouteWithChildren
  OnboardingIntakeRoute: typeof OnboardingIntakeRouteWithChildren
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingAgreementRoute: OnboardingAgreementRouteWithChildren,
  OnboardingIntakeRoute: OnboardingIntakeRouteWithChildren,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  BuyersRoute: BuyersRoute,
  CommunitiesRoute: CommunitiesRoute,
  ContactRoute: ContactRoute,
  HomeLoansRoute: HomeLoansRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RealtorsRoute: RealtorsRoute,
  SellersRoute: SellersRoute,
  TermsRoute: TermsRoute,
  CommunitiesInventoryRoute: CommunitiesInventoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
