-- =========================================================================
-- AGREEMENTS TABLE
-- =========================================================================
CREATE TABLE public.agreements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_slug text NOT NULL,
  client_name text NOT NULL,
  client_email text,
  signature_data_url text NOT NULL,
  signed_at timestamptz NOT NULL DEFAULT now(),
  user_agent text,
  ip_address text,
  pdf_storage_path text,
  agreement_version text NOT NULL DEFAULT 'v1',
  status text NOT NULL DEFAULT 'signed' CHECK (status IN ('signed', 'void'))
);

CREATE INDEX agreements_client_slug_idx ON public.agreements(client_slug);
CREATE INDEX agreements_signed_at_idx ON public.agreements(signed_at DESC);

ALTER TABLE public.agreements ENABLE ROW LEVEL SECURITY;

-- No public SELECT/INSERT/UPDATE/DELETE policies.
-- All reads/writes happen via server functions using the service role key,
-- which bypasses RLS. RLS-on with no policies = locked to anon/authenticated.

-- =========================================================================
-- INTAKE SUBMISSIONS TABLE
-- =========================================================================
CREATE TABLE public.intake_submissions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_slug text NOT NULL,
  client_name text,
  client_email text,
  form_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  current_section_index integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'submitted')),
  is_complete boolean NOT NULL DEFAULT false,
  submitted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  -- One draft + one submitted row per client. After submit, a fresh draft can
  -- be opened without overwriting the historical submission.
  CONSTRAINT intake_submissions_client_status_unique UNIQUE (client_slug, status)
);

CREATE INDEX intake_submissions_client_slug_idx ON public.intake_submissions(client_slug);

ALTER TABLE public.intake_submissions ENABLE ROW LEVEL SECURITY;

-- Server-only access. The browser never touches this table directly — the
-- intake page calls server functions (saveIntake, submitIntake, getIntake)
-- which use the service role client. No public policies needed.

-- =========================================================================
-- updated_at TRIGGER
-- =========================================================================
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER intake_submissions_set_updated_at
BEFORE UPDATE ON public.intake_submissions
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- =========================================================================
-- STORAGE BUCKETS
-- =========================================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('signed-agreements', 'signed-agreements', false)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public)
VALUES ('intake-uploads', 'intake-uploads', false)
ON CONFLICT (id) DO NOTHING;

-- signed-agreements: server-only. No public policies — service role bypasses RLS.

-- intake-uploads: public can INSERT (browser file uploads from intake form);
-- SELECT requires signed URL minted server-side.
CREATE POLICY "Anyone can upload to intake-uploads"
ON storage.objects
FOR INSERT
TO anon, authenticated
WITH CHECK (bucket_id = 'intake-uploads');

-- No public SELECT on intake-uploads — files are read only via signed URLs
-- generated by server functions using the service role.